import { ArrowRight, Check, CheckCircle2, Circle, Home, RotateCcw, UsersRound } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { useTraining } from '../app/TrainingContext'
import { Avatar } from '../components/ui/Avatar'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { trainingService } from '../services/trainingService'

export function SessionResultPage() {
  const navigate = useNavigate()
  const { sessionId = 'mock-session' } = useParams()
  const { session, messages } = useTraining()
  const persona = trainingService.getPersona(session?.personaId)
  const mode = session?.mode ?? 'CUSTOMER_FIRST'
  const result = trainingService.getResult(sessionId, messages.filter((message) => message.sender === 'SALE').length)

  return <div className="mx-auto max-w-5xl"><div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-5 text-xs font-extrabold uppercase tracking-[0.18em] text-emerald-600">Session complete</p><h1 className="mt-2 text-balance text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Hoàn thành phiên luyện tập</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">Bạn đã hoàn thành một tình huống bán hàng 1vs1. Dưới đây là tóm tắt mô phỏng của phiên.</p></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><div className="space-y-5"><Card className="p-5"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400">Khách hàng</p><div className="mt-4 flex items-center gap-4"><Avatar initials={persona.initials} color={persona.color} size="lg" /><div><h2 className="text-xl font-extrabold text-slate-950">{persona.displayName}</h2><p className="font-semibold text-blue-700">{persona.role}</p><p className="text-sm text-slate-500">{persona.customerType}</p></div></div></Card><Card className="p-5"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400">Tóm tắt phiên</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Lượt trao đổi của bạn</dt><dd className="font-extrabold text-slate-900">{result.turnCount}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Thời lượng</dt><dd className="font-extrabold text-slate-900">{result.durationLabel}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Chế độ</dt><dd className="text-xs font-extrabold text-blue-700">{mode}</dd></div></dl></Card></div>
      <div className="space-y-5"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400">Kết quả deal mô phỏng</p><h2 className="mt-2 text-xl font-extrabold text-slate-950">Khách hàng đang quan tâm</h2></div><Badge className="bg-emerald-50 text-emerald-700">CUSTOMER_INTERESTED</Badge></div><p className="mt-3 text-sm leading-6 text-slate-500">Đây là trạng thái mô phỏng từ phiên FE, không phải điểm đánh giá năng lực.</p></div><div className="grid gap-0 sm:grid-cols-2"><div className="p-5 sm:border-r sm:border-slate-100"><p className="text-sm font-extrabold text-slate-800">Chủ đề đã xử lý</p><div className="mt-4 space-y-3">{result.completedTopics.map((item) => <div key={item} className="flex items-center gap-2.5 text-sm font-semibold text-slate-700"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check className="h-3 w-3" /></span>{item}</div>)}</div></div><div className="border-t border-slate-100 p-5 sm:border-t-0"><p className="text-sm font-extrabold text-slate-800">Chủ đề còn thiếu</p><div className="mt-4 space-y-3">{result.missingTopics.map((item) => <div key={item} className="flex items-center gap-2.5 text-sm text-slate-500"><Circle className="h-5 w-5" />{item}</div>)}</div></div></div></Card>
      <Card className="p-5"><p className="text-sm font-extrabold text-slate-800">Tín hiệu trong phiên</p><div className="mt-4 flex flex-wrap gap-2">{result.signals.map((signal) => <Badge key={signal} className="bg-blue-50 text-blue-700"><Check className="mr-1.5 h-3.5 w-3.5" />{signal}</Badge>)}</div></Card></div></div>
    <div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button variant="secondary" icon={<RotateCcw className="h-4 w-4" />} onClick={() => navigate(`/practice/new?personaId=${persona.id}`)}>Luyện tập lại</Button><Button variant="secondary" icon={<UsersRound className="h-4 w-4" />} onClick={() => navigate('/customers')}>Chọn khách hàng khác</Button><Button icon={<Home className="h-4 w-4" />} onClick={() => navigate('/dashboard')}>Về trang chủ<ArrowRight className="h-4 w-4" /></Button></div>
  </div>
}
