import { ArrowRight, Check, CheckCircle2, Circle, Home, RotateCcw, UsersRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useTraining } from '../app/TrainingContext'
import { Avatar } from '../components/ui/Avatar'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { LoadingState } from '../components/ui/Feedback'

const topicLabels: Record<string, string> = { product_model: 'Sản phẩm', configuration: 'Cấu hình', price: 'Giá', stock: 'Tồn kho', delivery: 'Giao hàng', warranty: 'Bảo hành', payment: 'Thanh toán', invoice_or_document: 'Hóa đơn / tài liệu', next_step: 'Bước tiếp theo' }
const outcomeLabels: Record<string, string> = { not_ready: 'Đang khám phá nhu cầu', quote_requested: 'Khách hàng yêu cầu báo giá', ready_to_close: 'Sẵn sàng chốt bước tiếp theo', payment_info_requested: 'Khách hàng hỏi thanh toán', hold_requested: 'Khách hàng muốn giữ hàng', customer_committed: 'Khách hàng đã cam kết', pending_approval: 'Đang chờ phê duyệt', pending_payment: 'Đang chờ thanh toán', closed_won_simulated: 'Chốt thành công mô phỏng', closed_lost: 'Chưa đạt thỏa thuận', stalled: 'Hội thoại chưa tiến triển' }
const signalLabels: Record<string, string> = { quote_request_signal: 'Yêu cầu báo giá', payment_request_signal: 'Yêu cầu thông tin thanh toán', purchase_intent_signal: 'Tín hiệu mua hàng', hold_request_signal: 'Yêu cầu giữ hàng', invoice_request_signal: 'Yêu cầu hóa đơn' }
const humanize = (value: string, labels: Record<string, string>) => labels[value] ?? value.replaceAll('_', ' ')

export function SessionResultPage() {
  const navigate = useNavigate()
  const { sessionId = '' } = useParams()
  const { session, loadSession } = useTraining()
  const [loading, setLoading] = useState(session?.id !== sessionId)
  const [error, setError] = useState('')
  useEffect(() => {
    if (!sessionId || session?.id === sessionId) { setLoading(false); return }
    loadSession(sessionId).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Không thể tải kết quả phiên.')).finally(() => setLoading(false))
  }, [loadSession, session?.id, sessionId])
  if (loading) return <LoadingState label="Đang tải kết quả phiên..." />
  if (!session || session.id !== sessionId) return <Card className="mx-auto max-w-lg p-6 text-center"><h1 className="font-extrabold">Không thể tải kết quả</h1><p className="mt-2 text-sm text-red-600">{error}</p><Button className="mt-5" onClick={() => navigate('/customers')}>Chọn khách hàng</Button></Card>
  if (!session.result) return <Card className="mx-auto max-w-lg p-6 text-center"><h1 className="text-xl font-extrabold">Phiên chưa kết thúc</h1><p className="mt-2 text-sm text-slate-500">Kết quả chỉ được tạo khi phiên đã hoàn thành.</p><Button className="mt-5" onClick={() => navigate(`/practice/${session.id}`)}>Quay lại phiên</Button></Card>
  const { persona, mode, result } = session
  const duration = result.durationSeconds < 60 ? `${result.durationSeconds} giây` : `${Math.floor(result.durationSeconds / 60)} phút ${result.durationSeconds % 60} giây`

  return <div className="mx-auto max-w-5xl"><div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-5 text-xs font-extrabold uppercase tracking-[0.18em] text-emerald-600">Session complete</p><h1 className="mt-2 text-balance text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Hoàn thành phiên luyện tập</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">Bản tóm tắt dưới đây được tạo từ trạng thái deterministic của runtime, không dùng evaluator.</p></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><div className="space-y-5"><Card className="p-5"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400">Khách hàng</p><div className="mt-4 flex items-center gap-4"><Avatar initials={persona.initials} color={persona.color} size="lg" /><div><h2 className="text-xl font-extrabold text-slate-950">{persona.displayName}</h2><p className="font-semibold text-blue-700">{persona.role}</p><p className="text-sm text-slate-500">{persona.customerType}</p></div></div></Card><Card className="p-5"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400">Tóm tắt phiên</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Lượt trao đổi của bạn</dt><dd className="font-extrabold text-slate-900">{result.turnCount}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Thời lượng</dt><dd className="font-extrabold text-slate-900">{duration}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Chế độ</dt><dd className="text-xs font-extrabold text-blue-700">{mode}</dd></div></dl></Card></div>
      <div className="space-y-5"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400">Kết quả deal mô phỏng</p><h2 className="mt-2 text-xl font-extrabold text-slate-950">{humanize(result.outcome, outcomeLabels)}</h2></div><Badge className="bg-emerald-50 text-emerald-700">{result.outcome}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-500">Training status: <span className="font-bold">{result.trainingStatus}</span>. Đây không phải điểm đánh giá năng lực.</p></div><div className="grid gap-0 sm:grid-cols-2"><div className="p-5 sm:border-r sm:border-slate-100"><p className="text-sm font-extrabold text-slate-800">Chủ đề đã xử lý</p><div className="mt-4 space-y-3">{result.resolvedTopics.length ? result.resolvedTopics.map((item) => <div key={item} className="flex items-center gap-2.5 text-sm font-semibold text-slate-700"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check className="h-3 w-3" /></span>{humanize(item, topicLabels)}</div>) : <p className="text-sm text-slate-500">Chưa có chủ đề được xác nhận.</p>}</div></div><div className="border-t border-slate-100 p-5 sm:border-t-0"><p className="text-sm font-extrabold text-slate-800">Chủ đề còn thiếu</p><div className="mt-4 space-y-3">{result.missingTopics.map((item) => <div key={item} className="flex items-center gap-2.5 text-sm text-slate-500"><Circle className="h-5 w-5" />{humanize(item, topicLabels)}</div>)}</div></div></div></Card>
      <Card className="p-5"><p className="text-sm font-extrabold text-slate-800">Tín hiệu deterministic trong phiên</p><div className="mt-4 flex flex-wrap gap-2">{result.signals.length ? result.signals.map((signal) => <Badge key={signal} className="bg-blue-50 text-blue-700"><Check className="mr-1.5 h-3.5 w-3.5" />{humanize(signal, signalLabels)}</Badge>) : <p className="text-sm text-slate-500">Runtime chưa ghi nhận tín hiệu đáng tin cậy.</p>}</div></Card></div></div>
    <div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button variant="secondary" icon={<RotateCcw className="h-4 w-4" />} onClick={() => navigate(`/practice/new?personaId=${persona.id}`)}>Luyện tập lại</Button><Button variant="secondary" icon={<UsersRound className="h-4 w-4" />} onClick={() => navigate('/customers')}>Chọn khách hàng khác</Button><Button icon={<Home className="h-4 w-4" />} onClick={() => navigate('/dashboard')}>Về trang chủ<ArrowRight className="h-4 w-4" /></Button></div>
  </div>
}
